In [ ]:
import numpy as np


In [ ]:
np.__version__

'2.0.2'

In [ ]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [ ]:
arr=np.array([1,2,3,4])

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
l=[1,2,3,4,"ram"]

In [ ]:
arr=np.array(l)
print(arr) # all elements of l became string i.e type casting will happen here


['1' '2' '3' '4' 'ram']


In [ ]:
arr.ndim # this gives no of dimensions of array

1

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr.ndim) # it as it is matrix its is 2d so 2 dimensions

2


In [ ]:
print(arr.T.ndim) # it as it is matrix its is 2d so 2 dimensions

2


In [ ]:
mat=np.matrix([1,2,3,4])
mat

matrix([[1, 2, 3, 4]])

In [ ]:
print(mat.ndim)

2


In [ ]:
mat2=np.matrix([[1,2,3,4],[5,6,7,8]])
print(mat2)

[[1 2 3 4]
 [5 6 7 8]]


note: matrix will be always 2d


In [ ]:
np.matrix([[[1,2,4]]]) # as you can see if 3d is given not accepting and if only 1d is passed then it is taking as  2d only

ValueError: matrix must be 2-dimensional

In [ ]:
l=[1,2,4]
arr=np.asarray(l)
print(type(arr))
print(type(l))

<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
a=np.array([1,2,3,4])
b=a.copy() # deep copy
a[0]=2
print(a)
print(b)

[2 2 3 4]
[1 2 3 4]


In [ ]:
arr=np.fromfunction(lambda i,j: i==j,(3,3))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)

[[ True False False]
 [False  True False]
 [False False  True]]
2
(3, 3)
9


In [ ]:
arr1=np.fromiter((i for i in range(5)),int)
arr1

array([0, 1, 2, 3, 4])

In [ ]:
arr1=np.fromiter([1,2,3,4,5],dtype="<U3")
# arr1 = np.fromiter((str(i) for i in range(5)), dtype='<U3')

print(arr1)


['1' '2' '3' '4' '5']


In [ ]:
arr3= np.fromstring("22 23 24",dtype=int,sep=" ")
print(arr3)

[22 23 24]


In [ ]:
np.arange(1,10,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [ ]:
np.linspace(1,5,10) # gives 10 numbers between 1 and 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
import numpy as np


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
b=np.zeros((10,10),dtype=int)
print(b)
print(b.ndim)
print(b.shape)
print(b.size)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
2
(10, 10)
100


In [ ]:
b=np.ones((10,10),dtype=int)
print(b)
print(b.ndim)
print(b.shape)
print(b.size)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
2
(10, 10)
100


In [ ]:
c=np.zeros((2,3,3),dtype=int)
print(c)
print(c.ndim)
print(c.shape)
print(c.size)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
3
(2, 3, 3)
18


In [ ]:
print(np.zeros((5,5))+5) #lly  multiplicationa and minus


[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [ ]:
print(np.eye(5)) #returns a 2d identity matrix with order 5 x 5


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
import numpy as np
print(np.empty(5)) #here elements are assigned using values that are peresnt in mempory already

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
import random
print(random.choice([1,2,3,4,5]))
print(random.choice("Ajay"))
print(random.randrange(1,10))
print(random.random()) #here a no is generated  between [0,1) (uniform distribution)
l=[1,2,3,4,5]
print(random.shuffle(l))
print(l)
print(random.uniform(2,10))

4
A
8
0.843463288755927
None
[3, 2, 1, 4, 5]
8.872635164071198


In [ ]:
# now random numbers using np

l1=np.random.random_sample(5)
l2=np.random.random_sample((5,))
l3=np.random.random_sample((2,3))
print(l1,"\n",l2,"\n",l3)
print(l1.shape,"\n",l2.shape,"\n",l3.shape)
print(l1.ndim,"\n",l2.ndim,"\n",l3.ndim)


[0.34430447 0.08812066 0.69757345 0.79707623 0.95001744] 
 [0.50083398 0.75184437 0.0489597  0.8222863  0.22587827] 
 [[0.68485751 0.84449185 0.64680314]
 [0.9101245  0.95422495 0.42300689]]
(5,) 
 (5,) 
 (2, 3)
1 
 1 
 2


In [ ]:
print(np.random.rand(1))
l1=np.random.rand(1,3)
print(l1)
print(l1.shape)
print(l1.T.shape)

[0.39360036]
[[0.75572067 0.27773912 0.77861597]]
(1, 3)
(3, 1)


In [ ]:
print(np.random.randn(2,3))  # here this uses normal distribution

[[-0.7010226   1.79044874  0.95908926]
 [-1.09327493  0.37651692  0.31453982]]


In [ ]:
l1=np.random.randint(1,5,size=5)
print(l1)
print(l1.shape)
print(l1.ndim)
l1=np.random.randint(1,5,size=(5,))
print(l1)
print(l1.shape)
print(l1.ndim)


[4 1 4 2 2]
(5,)
1
[3 1 4 3 2]
(5,)
1


In [ ]:
l1=np.random.randint(1,5,size=(3,4))
print(l1)
print(l1.shape)

[[3 4 4 2]
 [3 1 2 1]
 [1 3 4 3]]
(3, 4)


In [ ]:
arr=np.random.randint(1,10,(3,4))
print(arr)
print(arr.reshape(2,6)) # here 2 * 6 be equal to 3 * 4 i.e array size should be preserved
print(arr)

[[9 3 7 4]
 [7 5 4 7]
 [2 7 7 5]]
[[9 3 7 4 7 5]
 [4 7 2 7 7 5]]
[[9 3 7 4]
 [7 5 4 7]
 [2 7 7 5]]


In [ ]:
# here if we dont know row or col count then we can give -ve values in that place which will automate that task but only one unknown dimension
print(arr.reshape(6,-1))

[[9 3]
 [7 4]
 [7 5]
 [4 7]
 [2 7]
 [7 5]]


In [ ]:
print(arr.reshape(-2,1))


[[9]
 [3]
 [7]
 [4]
 [7]
 [5]
 [4]
 [7]
 [2]
 [7]
 [7]
 [5]]


In [ ]:
arr2=arr.reshape(-1,1,6) # i.e 6 cols 1 row and 2 of these
print(arr2)
for i in arr2:
  for j in i:
    print(j)

print(arr2[0][0][1])

[[[9 3 7 4 7 5]]

 [[4 7 2 7 7 5]]]
[9 3 7 4 7 5]
[4 7 2 7 7 5]
3


In [ ]:
arr1=np.random.randint(1,10,(4,6))
print(arr1)

[[9 1 6 2 2 5]
 [5 2 8 5 7 5]
 [3 7 2 4 7 9]
 [1 2 7 6 1 5]]


In [ ]:
arr1>3

array([[ True, False,  True, False, False,  True],
       [ True, False,  True,  True,  True,  True],
       [False,  True, False,  True,  True,  True],
       [False, False,  True,  True, False,  True]])

In [ ]:
arr1[arr1>3] # selects all the elements that are true in above mat

array([9, 6, 5, 5, 8, 5, 7, 5, 7, 4, 7, 9, 7, 6, 5])

In [ ]:
arr1[0:2,0:3]

array([[9, 1, 6],
       [5, 2, 8]])

In [ ]:
arr1[0:3,[2,-1]] # here it takes from [0,3) row and 2, last(-1) col lly can be used for rows too

array([[6, 5],
       [8, 5],
       [2, 9]])

In [ ]:
arr1[[1,2],[2,-1]]

array([8, 9])

In [ ]:
print(arr1[1,2])
print(arr1[2,-1])

8
9


In [ ]:
arr1=np.random.randint(1,10,(4,6))
arr2=np.random.randint(1,10,(4,6))


In [ ]:
arr1*arr2 #index wise multiplication lly division

array([[56, 16, 40, 56, 40,  3],
       [12, 30, 16, 63, 45, 12],
       [ 3, 18, 35, 16, 21,  3],
       [14, 18, 42,  9, 25,  4]])

In [ ]:
4/0

ZeroDivisionError: division by zero

In [ ]:
arr1/0

/tmp/ipython-input-1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [ ]:
arr1=np.random.randint(1,10,(3,3))
arr2=np.random.randint(1,10,(3,3))
print(arr1@arr2) # matrix multiplication
print(np.dot(arr1,arr2)) # matrix multiplication

[[ 47  50  38]
 [ 75 132  78]
 [ 73 137  85]]
[[ 47  50  38]
 [ 75 132  78]
 [ 73 137  85]]


In [ ]:
#broadcasting

In [ ]:
arr=np.zeros((3,3),dtype=int)

In [ ]:
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
arr+5 # here 1st 5 boradcasted into 3 col single dim array and then it will broadcasted into 3 mat each represnting each row

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
a=np.array([1,2,3])

In [ ]:
arr+[1,2,3] #here [1,2,3] will be broad casted into 3 matices each represnting each row

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
arr+a

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
arr=np.random.randint(1,10,(4,6))
print(arr)
print(arr.T)

[[2 7 6 9 2 5]
 [1 7 9 5 9 9]
 [8 7 6 5 7 6]
 [9 6 1 8 8 4]]
[[2 1 8 9]
 [7 7 7 6]
 [6 9 6 1]
 [9 5 5 8]
 [2 9 7 8]
 [5 9 6 4]]


In [2]:
import numpy as np
arr=np.random.randint(1,10,(4,6))
arr

array([[5, 8, 5, 5, 7, 7],
       [3, 2, 3, 4, 1, 4],
       [6, 8, 3, 2, 4, 6],
       [5, 4, 9, 1, 1, 6]])

In [5]:
arr.flatten()

array([5, 8, 5, 5, 7, 7, 3, 2, 3, 4, 1, 4, 6, 8, 3, 2, 4, 6, 5, 4, 9, 1,
       1, 6])

In [15]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [16]:
arr.ndim


1

In [17]:
arr.shape

(4,)

In [14]:
arr1=np.expand_dims(arr,axis=0) # increase the dimension by 1 in the provided axix,0 means rows(x axis) and 1 means cols (y axis)
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[[1 2 3 4]]
2
(1, 4)


In [18]:
arr2=np.expand_dims(arr,axis=1) # increase the dimension by 1 in the provided axix,0 means rows(x axis) and 1 means cols (y axis)
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1]
 [2]
 [3]
 [4]]
2
(4, 1)


In [19]:
arr=np.zeros((3,4))
print(arr)
print(arr.ndim)
print(arr.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2
(3, 4)


In [20]:
arr1=np.expand_dims(arr,axis=0) # increase the dimension by 1 in the provided axix,0 means rows(x axis) and 1 means cols (y axis)
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3
(1, 3, 4)


In [26]:
arr2=np.expand_dims(arr,axis=1) # increase the dimension by 1 in the provided axix,0 means rows(x axis) and 1 means cols (y axis)
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]]
3
(3, 1, 4)


In [29]:
arr3=arr2.reshape((2,2,3))
print(arr3)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [32]:
arr4=np.expand_dims(arr3,axis=0)
print(arr4)
print(arr4.shape)

[[[[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]]]
(1, 2, 2, 3)


In [33]:
arr5=np.expand_dims(arr3,axis=1)
print(arr5)
print(arr5.shape)

[[[[0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]]]]
(2, 1, 2, 3)


In [37]:
# now to remove a dimension
arr3=np.squeeze(arr4,axis=0)
print(arr3)
print(arr3.shape)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
(2, 2, 3)


In [39]:
# now to remove a dimension
arr3=np.squeeze(arr5,axis=1)
print(arr3)
print(arr3.shape)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
(2, 2, 3)


In [47]:
a=np.array([[1,2,3],[4,5,6]])

In [48]:
print(np.repeat(a,2))

[1 1 2 2 3 3 4 4 5 5 6 6]


In [49]:
print(np.repeat(a,3))

[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6]


In [50]:
print(np.repeat(a,2,axis=0))

[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]]


In [51]:
print(np.repeat(a,2,axis=1))

[[1 1 2 2 3 3]
 [4 4 5 5 6 6]]


In [53]:
np.roll(a,1)

array([[6, 1, 2],
       [3, 4, 5]])

In [54]:
np.roll(a,-1)

array([[2, 3, 4],
       [5, 6, 1]])

In [57]:
np.roll(a,1,axis=0)

array([[4, 5, 6],
       [1, 2, 3]])

In [58]:
np.roll(a,1,axis=1)

array([[3, 1, 2],
       [6, 4, 5]])

In [59]:
d=np.array(['pw','skills'])

In [60]:
np.char.upper(d)

array(['PW', 'SKILLS'], dtype='<U6')

In [61]:
np.char.capitalize(d)

array(['Pw', 'Skills'], dtype='<U6')

In [63]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [64]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [70]:
np.log(np.e)

np.float64(1.0)

In [71]:
np.log10(10)

np.float64(1.0)

In [72]:
np.exp(10)

np.float64(22026.465794806718)

In [74]:
np.power(a,2)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
# np.max ,np.mean, np.std, np.var ,np.mod(arr1,arr2),np.sqrt()

In [75]:
#np.sort(arr)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
f=a.flatten()
f

array([1, 2, 3, 4, 5, 6])

In [80]:
np.searchsorted(f,2.5) # returns index where the given value to be inserted to maintain order

np.int64(2)

In [83]:
g=np.array([12,1,3])
np.searchsorted(g,10)

np.int64(3)

In [84]:
#np.count_nonzero(arr) gives no of non zero elements
#np.linalg.det
#np.linalg.solve
#np.linalg.inv
#etc are some linalg tools